name: Build Javadocs and Deploy to Github Pages
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up build JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'zulu'
          java-version: '24'
          check-latest: true
      - name: Build Javadoc
        run: ./mvnw -B -V -e javadoc:javadoc
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          folder: target/site/apidocs
          target-folder: ${{github.ref_name}}
