# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore: 
      - '**.md'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.m2/wrapper
        key: ${{ runner.os }}-build-maven-${{ hashFiles('**/pom.xml', '**/maven-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-build-maven-
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
        check-latest: true
    - name: Build with Maven
      run: ./mvnw -B -V -e verify -DskipTests=true -DskipITs=true
    - name: Archive target directory
      run: tar -cf target.tar target
    - name: Upload target directory archive
      uses: actions/upload-artifact@v4
      with:
        name: build_target
        path: target.tar
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '17', '21', '22']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.m2/wrapper
        key: ${{ runner.os }}-test-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml', '**/maven-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-test-${{ matrix.java }}-maven-
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        check-latest: true
    - name: Download target directory archive
      uses: actions/download-artifact@v4
      with:
        name: build_target
    - name: Extract target directory archive
      run: tar -xf target.tar
    - name: Test with Maven
      run: ./mvnw -B -V -e -Pcoverage verify -Denforcer.skip=true -Dmaven.resources.skip=true -Dflatten.skip=true -Dmaven.main.skip=true -Dbnd.skip=true -Dassembly.skipAssembly=true -Dmaven.javadoc.skip=true -Dcyclonedx.skip=true -Dformatter.skip=true -Dforbiddenapis.skip=true -DskipTests=false -DskipITs=false
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: java-${{ matrix.java }}-testresults
        path: |
          **/target/surefire-reports/
          **/target/failsafe-reports/
          **/target/site/jacoco/
          **/target/site/jacoco-it/
      if: always()
