name: Release with Maven

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    # Runs a set of commands using the runners shell
    - name: Execute Release
      env:
        RELEASE_BRANCH_NAME: "release"

        GPG_ENABLED: "true"
        GPG_KEY_ID: ${{ secrets.GPG_ID }}
        GPG_KEY: ${{ secrets.GPG_KEY }}

        MAVEN_REPO_SERVER_ID: ${{ secrets.MVN_CENTRAL }}
        MAVEN_REPO_SERVER_USERNAME: ${{ secrets.MVN_CENTRAL_USER }}
        MAVEN_REPO_SERVER_PASSWORD: ${{ secrets.MVN_CENTRAL_PASSWORD }}
        MAVEN_ARGS: "-Dgpg.passphrase="

        GIT_RELEASE_BOT_NAME: "release-bot"
        GIT_RELEASE_BOT_EMAIL: "mwiede@gmx.de"

        GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}   
      run: sh ${{ github.workspace }}/.github/workflows/release.sh